"""
Django settings for ast_drf project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z7k15^mjpmb#6+547oe@%95t2njc%(%d5hr=$e&ua4on78+e1p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ast_books',
    'rest_framework',
    'drf_yasg',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ast_drf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ast_drf.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# логирование
LOGGING = {
    # первый ключ version всегда определяется как 1
    'version': 1,
    # контролирует работу существующей (стандартной) схемы логирования
    'disable_existing_loggers': False,
    'style': '{',
    # ключ — формат записи сообщений
    'formatters': {
        # (выводим в консоль) формат сообщения уровня DEBUG+ — время, уровень сообщения, сообщение
        'console_simple': {'format': '%(asctime)s %(levelname)s %(message)s'},
        # (выводим в консоль) формат сообщения уровня WARNING+ — время, уровень сообщения, сообщение, путь к источнику события
        'console_warning': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'},
        # (выводим в консоль) формат сообщения уровня ERROR и CRITICAL — время, уровень сообщения, сообщение, путь к источнику события, стэк ошибки
        'console_error': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'},
        # (выводим в файл general.log) формат сообщения уровня INFO+ — время, уровень сообщения, модуль, сообщение
        'general': {'format': '%(asctime)s %(levelname)s %(module)s %(message)s'},
        # (выводим в файл errors.log) формат сообщения уровня ERROR и CRITICAL — время, уровень сообщения, сообщение, путь к источнику события, стэк ошибки
        'error': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'},
        # (выводим в файл security.log) формат сообщения "уровня" SECURITY — время, уровень сообщения, модуль, сообщение
        'security': {'format': '%(asctime)s %(levelname)s %(module)s %(message)s'},
        # (отправляем на почту) формат сообщения уровня ERROR+ — время, уровень сообщения, сообщение, путь к источнику события
        'email': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'
                  },
    },
    # ключ — фильтры
    'filters': {
        # в консоль сообщения отправляются только при DEBUG = True
        'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'},
        # на почту и в файл general.log — только при DEBUG = False
        'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
    },
    # ключ — обработчики
    'handlers': {
        # обработчик вывода сообщений уровня DEBUG+ в консоль
        'console_simple': {
            # уровень применения
            'level': 'DEBUG',
            # применяемый фильтр
            'filters': ['require_debug_true'],
            # обработчик, отправляющий сообщения в консоль
            'class': 'logging.StreamHandler',
            # применяемый формат вывода
            'formatter': 'console_simple'},
        # обработчик вывода сообщений уровня WARNING+ в консоль
        'console_warning': {
            # уровень применения
            'level': 'WARNING',
            # применяемый фильтр
            'filters': ['require_debug_true'],
            # обработчик, отправляющий сообщения в консоль
            'class': 'logging.StreamHandler',
            # применяемый формат вывода
            'formatter': 'console_warning'},
        # обработчик вывода сообщений уровня ERROR и CRITICAL в консоль
        'console_error': {
            # уровень применения
            'level': 'ERROR',
            # применяемый фильтр
            'filters': ['require_debug_true'],
            # обработчик, отправляющий сообщения в консоль
            'class': 'logging.StreamHandler',
            # применяемый формат вывода
            'formatter': 'console_error'},
        # обработчик вывода сообщений уровня INFO+ в файл general.log
        'general': {
            # уровень применения
            'level': 'INFO',
            # применяемый фильтр
            'filters': ['require_debug_false'],
            # обработчик, отправляющий сообщения в файл
            'class': 'logging.FileHandler',
            # имя файла, в который отправляем сообщение
            'filename': 'general.log',
            # применяемый формат вывода
            'formatter': 'general'},
        # обработчик вывода сообщений уровня ERROR+ в файл errors.log
        'error': {
            # уровень применения
            'level': 'ERROR',
            # обработчик, отправляющий сообщения в файл
            'class': 'logging.FileHandler',
            # имя файла, в который отправляем сообщение
            'filename': 'errors.log',
            # применяемый формат вывода
            'formatter': 'error'},
        # обработчик вывода сообщений, связанных с безопасностью (security), в файл security.log
        'security': {
            # уровень применения
            'level': 'DEBUG',
            # обработчик, отправляющий сообщения в файл
            'class': 'logging.FileHandler',
            # имя файла, в который отправляем сообщение
            'filename': 'security.log',
            # применяемый формат вывода
            'formatter': 'security'},
        # обработчик вывода сообщений уровня ERROR+, отправляемых по почте
        'mail_admins': {
            # уровень применения
            'level': 'ERROR',
            # применяемый фильтр
            'filters': ['require_debug_false'],
            # обработчик, отправляющий сообщения по почте
            'class': 'django.utils.log.AdminEmailHandler',
            # применяемый формат вывода
            'formatter': 'email'
        },
    },
    # ключ — логгеры
    'loggers': {
        #  регистратор
        'django': {
            # отправляет на консоль и в файл
            'handlers': ['console_simple', 'console_warning', 'console_error', 'general'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.request': {
            # отправляет в файл и на почту
            'handlers': ['error', 'mail_admins'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.server': {
            # отправляет в файл и на почту
            'handlers': ['error', 'mail_admins'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.template': {
            # отправляет в файл
            'handlers': ['error'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.db.backends': {
            # отправляет в файл
            'handlers': ['error'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.security': {
            # отправляет в файл
            'handlers': ['security'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        }
    }
}

CRONJOBS = [
    ('0 0 */1 * *', 'ast_books.management.commands.update_reviews.Command'),
]
