"""
Django settings for ast_drf project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z7k15^mjpmb#6+547oe@%95t2njc%(%d5hr=$e&ua4on78+e1p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ast_books',
    'rest_framework',
    'drf_yasg',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ast_drf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ast_drf.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': dj_database_url.config(
#         default='sqlite:///db.sqlite3',  # Значение по умолчанию, если переменная DATABASE_URL не задана
#         conn_max_age=600,
#         ssl_require=True  # Обязательно, если вы используете защищённое соединение (например, на Heroku/Render)
#     )
# }

# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL')
#     )
# }

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
}

# логирование
LOGGING = {
    # первый ключ version всегда определяется как 1
    'version': 1,
    # контролирует работу существующей (стандартной) схемы логирования
    'disable_existing_loggers': False,
    'style': '{',
    # ключ — формат записи сообщений
    'formatters': {
        # (выводим в консоль) формат сообщения уровня DEBUG+ — время, уровень сообщения, сообщение
        'console_simple': {'format': '%(asctime)s %(levelname)s %(message)s'},
        # (выводим в консоль) формат сообщения уровня WARNING+ — время, уровень сообщения, сообщение, путь к источнику события
        'console_warning': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'},
        # (выводим в консоль) формат сообщения уровня ERROR и CRITICAL — время, уровень сообщения, сообщение, путь к источнику события, стэк ошибки
        'console_error': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'},
        # (выводим в файл general.log) формат сообщения уровня INFO+ — время, уровень сообщения, модуль, сообщение
        'general': {'format': '%(asctime)s %(levelname)s %(module)s %(message)s'},
        # (выводим в файл errors.log) формат сообщения уровня ERROR и CRITICAL — время, уровень сообщения, сообщение, путь к источнику события, стэк ошибки
        'error': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'},
        # (выводим в файл security.log) формат сообщения "уровня" SECURITY — время, уровень сообщения, модуль, сообщение
        'security': {'format': '%(asctime)s %(levelname)s %(module)s %(message)s'},
        # (отправляем на почту) формат сообщения уровня ERROR+ — время, уровень сообщения, сообщение, путь к источнику события
        'email': {'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'
                  },
    },
    # ключ — фильтры
    'filters': {
        # в консоль сообщения отправляются только при DEBUG = True
        'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'},
        # на почту и в файл general.log — только при DEBUG = False
        'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
    },
    # ключ — обработчики
    'handlers': {
        # обработчик вывода сообщений уровня DEBUG+ в консоль
        'console_simple': {
            # уровень применения
            'level': 'DEBUG',
            # применяемый фильтр
            'filters': ['require_debug_true'],
            # обработчик, отправляющий сообщения в консоль
            'class': 'logging.StreamHandler',
            # применяемый формат вывода
            'formatter': 'console_simple'},
        # обработчик вывода сообщений уровня WARNING+ в консоль
        'console_warning': {
            # уровень применения
            'level': 'WARNING',
            # применяемый фильтр
            'filters': ['require_debug_true'],
            # обработчик, отправляющий сообщения в консоль
            'class': 'logging.StreamHandler',
            # применяемый формат вывода
            'formatter': 'console_warning'},
        # обработчик вывода сообщений уровня ERROR и CRITICAL в консоль
        'console_error': {
            # уровень применения
            'level': 'ERROR',
            # применяемый фильтр
            'filters': ['require_debug_true'],
            # обработчик, отправляющий сообщения в консоль
            'class': 'logging.StreamHandler',
            # применяемый формат вывода
            'formatter': 'console_error'},
        # обработчик вывода сообщений уровня INFO+ в файл general.log
        'general': {
            # уровень применения
            'level': 'INFO',
            # применяемый фильтр
            'filters': ['require_debug_false'],
            # обработчик, отправляющий сообщения в файл
            'class': 'logging.FileHandler',
            # имя файла, в который отправляем сообщение
            'filename': 'general.log',
            # применяемый формат вывода
            'formatter': 'general'},
        # обработчик вывода сообщений уровня ERROR+ в файл errors.log
        'error': {
            # уровень применения
            'level': 'ERROR',
            # обработчик, отправляющий сообщения в файл
            'class': 'logging.FileHandler',
            # имя файла, в который отправляем сообщение
            'filename': 'errors.log',
            # применяемый формат вывода
            'formatter': 'error'},
        # обработчик вывода сообщений, связанных с безопасностью (security), в файл security.log
        'security': {
            # уровень применения
            'level': 'DEBUG',
            # обработчик, отправляющий сообщения в файл
            'class': 'logging.FileHandler',
            # имя файла, в который отправляем сообщение
            'filename': 'security.log',
            # применяемый формат вывода
            'formatter': 'security'},
        # обработчик вывода сообщений уровня ERROR+, отправляемых по почте
        'mail_admins': {
            # уровень применения
            'level': 'ERROR',
            # применяемый фильтр
            'filters': ['require_debug_false'],
            # обработчик, отправляющий сообщения по почте
            'class': 'django.utils.log.AdminEmailHandler',
            # применяемый формат вывода
            'formatter': 'email'
        },
    },
    # ключ — логгеры
    'loggers': {
        #  регистратор
        'django': {
            # отправляет на консоль и в файл
            'handlers': ['console_simple', 'console_warning', 'console_error', 'general'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.request': {
            # отправляет в файл и на почту
            'handlers': ['error', 'mail_admins'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.server': {
            # отправляет в файл и на почту
            'handlers': ['error', 'mail_admins'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.template': {
            # отправляет в файл
            'handlers': ['error'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.db.backends': {
            # отправляет в файл
            'handlers': ['error'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        },
        # регистратор
        'django.security': {
            # отправляет в файл
            'handlers': ['security'],
            # сообщения логгера по иерархии (родительским логгерам)
            'propagate': True,
        }
    }
}

CRONJOBS = [
    ('0 0 */1 * *', 'ast_books.management.commands.update_reviews.Command'),
]

"""
Настройки библиотеки Jazzmin. С комментариями по каждой настройке. Закомментированные можно тестить.
"""
JAZZMIN_SETTINGS = {
    # заголовок окна (по умолчанию будет current_admin_site.site_title, если он отсутствует или отсутствует)
    "site_title": "АСТ Admin",
    # Заголовок на экране входа в систему (максимум 19 символов) (по умолчанию — current_admin_site.site_header,
    # если он отсутствует или отсутствует)
    "site_header": "АСТ",
    # Название бренда (максимум 19 символов) (по умолчанию current_admin_site.site_header,
    # если оно отсутствует или отсутствует)
    "site_brand": "АСТ",
    # # Название бренда (максимум 19 символов) (по умолчанию current_admin_site.site_header,
    # # если оно отсутствует или отсутствует)
    # "site_logo": "/logo.png",
    # # Логотип, используемый для вашего сайта, должен присутствовать в статических файлах,
    # # используется для логотипа формы входа (по умолчанию site_logo)
    # "login_logo": None,
    #
    # # Логотип для формы входа в темные темы (по умолчанию — login_logo)
    # "login_logo_dark": None,
    #
    # # Классы CSS, которые применяются к логотипу выше
    # "site_logo_classes": "img-circle",
    # # Относительный путь к значку вашего сайта, по умолчанию будет site_logo,
    # # если он отсутствует (в идеале 32x32 пикселей).
    # "site_icon": None,
    # Текст приветствия на экране входа в систему
    "welcome_sign": "Добро пожаловать в «АСТ»!",
    # Авторские права в нижнем колонтитуле
    "copyright": "TEAM 13",
    # # Список администраторов модели для поиска из панели поиска, панель поиска опускается, если она исключена
    # # Если вы хотите использовать одно поле поиска, вам не нужно использовать список,
    # # вы можете использовать простую строку
    # "search_model": ["auth.User", "auth.Group"],
    # Имя поля в модели пользователя, которое содержит аватар ImageField/URLField/Charfield или вызываемый объект,
    # который получает пользователя
    # "user_avatar": None,
    ############
    # Top Menu #
    ############
    # # Ссылки для размещения в верхнем меню
    # "topmenu_links": [
    #
    #     # Url that gets reversed (Permissions can be added)
    #     {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
    #
    #     # external url that opens in a new window (Permissions can be added)
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    #
    #     # model admin to link to (Permissions checked against model)
    #     {"model": "auth.User"},
    #
    #     # App with dropdown menu to all its models pages (Permissions checked against models)
    #     {"app": "books"},
    # ],
    #############
    # User Menu #
    #############
    # # Дополнительные ссылки для включения в меню пользователя в правом верхнем углу
    # # (тип URL-адреса «приложение» не разрешен)
    # "usermenu_links": [
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    #     {"model": "auth.user"}
    # ],
    #############
    # Side Menu #
    #############
    # Отображать ли боковое меню
    "show_sidebar": True,
    # Стоит ли автоматически расширять меню
    "navigation_expanded": True,
    # # Скрыть эти приложения при создании бокового меню, например (аутентификация)
    # "hide_apps": [],
    #
    # # Скрыть эти модели при создании бокового меню (например, auth.user)
    # "hide_models": [],
    # # Список приложений (и/или моделей) для заказа в базовом боковом меню
    # # (не обязательно содержать все приложения/модели)
    # "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    # # Пользовательские ссылки для добавления в группы приложений, привязанные к названию приложения.
    # "custom_links": {
    #     "books": [{
    #         "name": "Make Messages",
    #         "url": "make_messages",
    #         "icon": "fas fa-comments",
    #         "permissions": ["books.view_book"]
    #     }]
    # },
    # # Пользовательские значки для приложений/моделей бокового меню.
    # # См. https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13, 5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3. 1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2, 5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # # для получения полного списка бесплатных классов значков версии 5.13.0
    # "icons": {
    #     "auth": "fas fa-users-cog",
    #     "auth.user": "fas fa-user",
    #     "auth.Group": "fas fa-users",
    # },
    # # Значки, которые используются, если они не указаны вручную
    # "default_icon_parents": "fas fa-chevron-circle-right",
    # "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    # Используйте модальные окна вместо всплывающих окон (False по умолчанию)
    # "related_modal_active": True,
    #############
    # UI Tweaks #
    #############
    # # Относительные пути к пользовательским сценариям CSS/JS (должны присутствовать в статических файлах)
    # "custom_css": None,
    # "custom_js": None,
    # # Связывать ли шрифт с Fonts.googleapis.com (в противном случае используйте custom_css для указания шрифта)
    # "use_google_fonts_cdn": True,
    # Показывать ли настройщик пользовательского интерфейса на боковой панели
    "show_ui_builder": False,
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    # Отображение представления изменений в виде одной формы или вкладок, текущие параметры
    # - одинокий
    # - горизонтальные_табы (по умолчанию)
    # - вертикальные_табы
    # - складной
    # - карусель
    "changeform_format": "collapsible",
    # # переопределить формы изменений для каждого администратора модели
    # "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # # Добавляем раскрывающийся список языков в админку
    # "language_chooser": True,
}

"""
Настройки темы JAZZMIN — админка
"""

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "solar",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}

MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
