# Generated by Django 5.1.3 on 2024-12-21 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('audio_file', models.FileField(upload_to='audio/', verbose_name='Аудиофайл')),
            ],
            options={
                'verbose_name': 'Аудиофайл',
                'verbose_name_plural': 'Аудиофайлы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('price_url', models.URLField(blank=True, help_text='Ссылка на покупку книги', null=True, verbose_name='Ссылка на покупку')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('create', models.DateTimeField(verbose_name='Дата отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('pros', models.TextField(verbose_name='Плюсы')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='review_picture/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Картинка отзыва',
                'verbose_name_plural': 'Картинки отзывов',
            },
        ),
        migrations.CreateModel(
            name='BookPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='book_picture/', verbose_name='Изображение')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ast_books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Изображение страниц книги',
                'verbose_name_plural': 'Изображения страниц книги',
            },
        ),
    ]
